use std::fmt::Display;

#[allow(non_camel_case_types, dead_code)]
#[derive(Debug, PartialEq)]
pub enum Code {
    KEY_RESERVED,
    KEY_ESC,
    KEY_1,
    KEY_2,
    KEY_3,
    KEY_4,
    KEY_5,
    KEY_6,
    KEY_7,
    KEY_8,
    KEY_9,
    KEY_0,
    KEY_MINUS,
    KEY_EQUAL,
    KEY_BACKSPACE,
    KEY_TAB,
    KEY_Q,
    KEY_W,
    KEY_E,
    KEY_R,
    KEY_T,
    KEY_Y,
    KEY_U,
    KEY_I,
    KEY_O,
    KEY_P,
    KEY_LEFTBRACE,
    KEY_RIGHTBRACE,
    KEY_ENTER,
    KEY_LEFTCTRL,
    KEY_A,
    KEY_S,
    KEY_D,
    KEY_F,
    KEY_G,
    KEY_H,
    KEY_J,
    KEY_K,
    KEY_L,
    KEY_SEMICOLON,
    KEY_APOSTROPHE,
    KEY_GRAVE,
    KEY_LEFTSHIFT,
    KEY_BACKSLASH,
    KEY_Z,
    KEY_X,
    KEY_C,
    KEY_V,
    KEY_B,
    KEY_N,
    KEY_M,
    KEY_COMMA,
    KEY_DOT,
    KEY_SLASH,
    KEY_RIGHTSHIFT,
    KEY_KPASTERISK,
    KEY_LEFTALT,
    KEY_SPACE,
    KEY_CAPSLOCK,
    KEY_F1,
    KEY_F2,
    KEY_F3,
    KEY_F4,
    KEY_F5,
    KEY_F6,
    KEY_F7,
    KEY_F8,
    KEY_F9,
    KEY_F10,
    KEY_NUMLOCK,
    KEY_SCROLLLOCK,
    KEY_KP7,
    KEY_KP8,
    KEY_KP9,
    KEY_KPMINUS,
    KEY_KP4,
    KEY_KP5,
    KEY_KP6,
    KEY_KPPLUS,
    KEY_KP1,
    KEY_KP2,
    KEY_KP3,
    KEY_KP0,
    KEY_KPDOT,

    KEY_ZENKAKUHANKAKU,
    KEY_102ND,
    KEY_F11,
    KEY_F12,
    KEY_RO,
    KEY_KATAKANA,
    KEY_HIRAGANA,
    KEY_HENKAN,
    KEY_KATAKANAHIRAGANA,
    KEY_MUHENKAN,
    KEY_KPJPCOMMA,
    KEY_KPENTER,
    KEY_RIGHTCTRL,
    KEY_KPSLASH,
    KEY_SYSRQ,
    KEY_RIGHTALT,
    KEY_LINEFEED,
    KEY_HOME,
    KEY_UP,
    KEY_PAGEUP,
    KEY_LEFT,
    KEY_RIGHT,
    KEY_END,
    KEY_DOWN,
    KEY_PAGEDOWN,
    KEY_INSERT,
    KEY_DELETE,
    KEY_MACRO,
    KEY_MUTE,
    KEY_VOLUMEDOWN,
    KEY_VOLUMEUP,
    KEY_POWER, /* SC System Power Down */
    KEY_KPEQUAL,
    KEY_KPPLUSMINUS,
    KEY_PAUSE,
    KEY_SCALE, /* AL Compiz Scale (Expose) */

    KEY_KPCOMMA,
    KEY_HANGEUL,
    KEY_HANGUEL, // FIXME: same value as KEY_HANGEUL
    KEY_HANJA,
    KEY_YEN,
    KEY_LEFTMETA,
    KEY_RIGHTMETA,
    KEY_COMPOSE,

    KEY_STOP, /* AC Stop */
    KEY_AGAIN,
    KEY_PROPS, /* AC Properties */
    KEY_UNDO,  /* AC Undo */
    KEY_FRONT,
    KEY_COPY,  /* AC Copy */
    KEY_OPEN,  /* AC Open */
    KEY_PASTE, /* AC Paste */
    KEY_FIND,  /* AC Search */
    KEY_CUT,   /* AC Cut */
    KEY_HELP,  /* AL Integrated Help Center */
    KEY_MENU,  /* Menu (show menu) */
    KEY_CALC,  /* AL Calculator */
    KEY_SETUP,
    KEY_SLEEP,  /* SC System Sleep */
    KEY_WAKEUP, /* System Wake Up */
    KEY_FILE,   /* AL Local Machine Browser */
    KEY_SENDFILE,
    KEY_DELETEFILE,
    KEY_XFER,
    KEY_PROG1,
    KEY_PROG2,
    KEY_WWW, /* AL Internet Browser */
    KEY_MSDOS,
    KEY_COFFEE,         /* AL Terminal Lock/Screensaver */
    KEY_SCREENLOCK,     //FIXME: same as KEY_COFFEE
    KEY_ROTATE_DISPLAY, /* Display orientation for e.g. tablets */
    KEY_DIRECTION,      // FIXME: same as KEY_ROTATE_DISPLAY
    KEY_CYCLEWINDOWS,
    KEY_MAIL,
    KEY_BOOKMARKS, /* AC Bookmarks */
    KEY_COMPUTER,
    KEY_BACK,    /* AC Back */
    KEY_FORWARD, /* AC Forward */
    KEY_CLOSECD,
    KEY_EJECTCD,
    KEY_EJECTCLOSECD,
    KEY_NEXTSONG,
    KEY_PLAYPAUSE,
    KEY_PREVIOUSSONG,
    KEY_STOPCD,
    KEY_RECORD,
    KEY_REWIND,
    KEY_PHONE, /* Media Select Telephone */
    KEY_ISO,
    KEY_CONFIG,   /* AL Consumer Control Configuration */
    KEY_HOMEPAGE, /* AC Home */
    KEY_REFRESH,  /* AC Refresh */
    KEY_EXIT,     /* AC Exit */
    KEY_MOVE,
    KEY_EDIT,
    KEY_SCROLLUP,
    KEY_SCROLLDOWN,
    KEY_KPLEFTPAREN,
    KEY_KPRIGHTPAREN,
    KEY_NEW,  /* AC New */
    KEY_REDO, /* AC Redo/Repeat */

    KEY_F13,
    KEY_F14,
    KEY_F15,
    KEY_F16,
    KEY_F17,
    KEY_F18,
    KEY_F19,
    KEY_F20,
    KEY_F21,
    KEY_F22,
    KEY_F23,
    KEY_F24,

    KEY_PLAYCD,
    KEY_PAUSECD,
    KEY_PROG3,
    KEY_PROG4,
    KEY_ALL_APPLICATIONS, /* AC Desktop Show All Applications */
    KEY_DASHBOARD,        // FIXME: same as KEY_ALL_APPLICATIONS
    KEY_SUSPEND,
    KEY_CLOSE, /* AC Close */
    KEY_PLAY,
    KEY_FASTFORWARD,
    KEY_BASSBOOST,
    KEY_PRINT, /* AC Print */
    KEY_HP,
    KEY_CAMERA,
    KEY_SOUND,
    KEY_QUESTION,
    KEY_EMAIL,
    KEY_CHAT,
    KEY_SEARCH,
    KEY_CONNECT,
    KEY_FINANCE, /* AL Checkbook/Finance */
    KEY_SPORT,
    KEY_SHOP,
    KEY_ALTERASE,
    KEY_CANCEL, /* AC Cancel */
    KEY_BRIGHTNESSDOWN,
    KEY_BRIGHTNESSUP,
    KEY_MEDIA,

    KEY_SWITCHVIDEOMODE, /* Cycle between available video outputs (Monitor/LCD/TV-out/etc) */
    KEY_KBDILLUMTOGGLE,
    KEY_KBDILLUMDOWN,
    KEY_KBDILLUMUP,

    KEY_SEND,        /* AC Send */
    KEY_REPLY,       /* AC Reply */
    KEY_FORWARDMAIL, /* AC Forward Msg */
    KEY_SAVE,        /* AC Save */
    KEY_DOCUMENTS,

    KEY_BATTERY,

    KEY_BLUETOOTH,
    KEY_WLAN,
    KEY_UWB,

    KEY_UNKNOWN,

    KEY_VIDEO_NEXT,       /* drive next video source */
    KEY_VIDEO_PREV,       /* drive previous video source */
    KEY_BRIGHTNESS_CYCLE, /* brightness up, after max is min */
    KEY_BRIGHTNESS_AUTO, /* Set Auto Brightness: manual brightness control is off, rely on ambient */
    KEY_BRIGHTNESS_ZERO, // FIXME: same as KEY_BRIGHTNESS_AUTO
    KEY_DISPLAY_OFF,     /* display device to off state */

    KEY_WWAN,   /* Wireless WAN (LTE, UMTS, GSM, etc.) */
    KEY_WIMAX,  //FIXME: same as KEY_WWAN
    KEY_RFKILL, /* Key that controls all radios */

    KEY_MICMUTE, /* Mute / unmute the microphone */
}

#[derive(Debug)]
pub enum KeyError {
    UnknownCode,
}

impl Display for Code {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let key = match self {
            Code::KEY_RESERVED => "<reserved>",
            Code::KEY_ESC => "<escapte>",
            Code::KEY_1 => "1",
            Code::KEY_2 => "2",
            Code::KEY_3 => "3",
            Code::KEY_4 => "4",
            Code::KEY_5 => "5",
            Code::KEY_6 => "6",
            Code::KEY_7 => "7",
            Code::KEY_8 => "8",
            Code::KEY_9 => "9",
            Code::KEY_0 => "0",
            Code::KEY_MINUS => "-",
            Code::KEY_EQUAL => "=",
            Code::KEY_BACKSPACE => "<del>",
            Code::KEY_TAB => "<tab>",
            Code::KEY_Q => "q",
            Code::KEY_W => "w",
            Code::KEY_E => "e",
            Code::KEY_R => "r",
            Code::KEY_T => "t",
            Code::KEY_Y => "y",
            Code::KEY_U => "u",
            Code::KEY_I => "i",
            Code::KEY_O => "o",
            Code::KEY_P => "p",
            Code::KEY_LEFTBRACE => todo!(),
            Code::KEY_RIGHTBRACE => todo!(),
            Code::KEY_ENTER => "<enter>",
            Code::KEY_LEFTCTRL => "<lctrl>",
            Code::KEY_A => "a",
            Code::KEY_S => "s",
            Code::KEY_D => "d",
            Code::KEY_F => "f",
            Code::KEY_G => "g",
            Code::KEY_H => "h",
            Code::KEY_J => "j",
            Code::KEY_K => "k",
            Code::KEY_L => "l",
            Code::KEY_SEMICOLON => ";",
            Code::KEY_APOSTROPHE => todo!(),
            Code::KEY_GRAVE => todo!(),
            Code::KEY_LEFTSHIFT => "<lshift>",
            Code::KEY_BACKSLASH => todo!(),
            Code::KEY_Z => "z",
            Code::KEY_X => "x",
            Code::KEY_C => "c",
            Code::KEY_V => "v",
            Code::KEY_B => "b",
            Code::KEY_N => "n",
            Code::KEY_M => "m",
            Code::KEY_COMMA => todo!(),
            Code::KEY_DOT => todo!(),
            Code::KEY_SLASH => "/",
            Code::KEY_RIGHTSHIFT => "<rshift>",
            Code::KEY_KPASTERISK => todo!(),
            Code::KEY_LEFTALT => "<lalt>",
            Code::KEY_SPACE => " ",
            Code::KEY_CAPSLOCK => "<capslock>",
            Code::KEY_F1 => "F1",
            Code::KEY_F2 => "F2",
            Code::KEY_F3 => "F3",
            Code::KEY_F4 => "F4",
            Code::KEY_F5 => "F5",
            Code::KEY_F6 => "F6",
            Code::KEY_F7 => "F7",
            Code::KEY_F8 => "F8",
            Code::KEY_F9 => "F9",
            Code::KEY_F10 => "F10",
            Code::KEY_NUMLOCK => "<numlock>",
            Code::KEY_SCROLLLOCK => todo!(),
            Code::KEY_KP7 => "7",
            Code::KEY_KP8 => "8",
            Code::KEY_KP9 => "9",
            Code::KEY_KPMINUS => "-",
            Code::KEY_KP4 => "4",
            Code::KEY_KP5 => "5",
            Code::KEY_KP6 => "6",
            Code::KEY_KPPLUS => "+",
            Code::KEY_KP1 => "1",
            Code::KEY_KP2 => "2",
            Code::KEY_KP3 => "3",
            Code::KEY_KP0 => "0",
            Code::KEY_KPDOT => ".",
            Code::KEY_ZENKAKUHANKAKU => todo!(),
            Code::KEY_102ND => todo!(),
            Code::KEY_F11 => todo!(),
            Code::KEY_F12 => todo!(),
            Code::KEY_RO => todo!(),
            Code::KEY_KATAKANA => todo!(),
            Code::KEY_HIRAGANA => todo!(),
            Code::KEY_HENKAN => todo!(),
            Code::KEY_KATAKANAHIRAGANA => todo!(),
            Code::KEY_MUHENKAN => todo!(),
            Code::KEY_KPJPCOMMA => todo!(),
            Code::KEY_KPENTER => todo!(),
            Code::KEY_RIGHTCTRL => "<rctrl>",
            Code::KEY_KPSLASH => todo!(),
            Code::KEY_SYSRQ => todo!(),
            Code::KEY_RIGHTALT => "<ralt>",
            Code::KEY_LINEFEED => todo!(),
            Code::KEY_HOME => "<home>",
            Code::KEY_UP => "<up>",
            Code::KEY_PAGEUP => "<page_up>",
            Code::KEY_LEFT => "<left>",
            Code::KEY_RIGHT => "<right>",
            Code::KEY_END => "<end>",
            Code::KEY_DOWN => "<down>",
            Code::KEY_PAGEDOWN => "<page_down>",
            Code::KEY_INSERT => "<insert>",
            Code::KEY_DELETE => "<delete>",
            Code::KEY_MACRO => todo!(),
            Code::KEY_MUTE => "<mute>",
            Code::KEY_VOLUMEDOWN => "<vol_down>",
            Code::KEY_VOLUMEUP => "<vol_up>",
            Code::KEY_POWER => todo!(),
            Code::KEY_KPEQUAL => todo!(),
            Code::KEY_KPPLUSMINUS => todo!(),
            Code::KEY_PAUSE => todo!(),
            Code::KEY_SCALE => todo!(),
            Code::KEY_KPCOMMA => todo!(),
            Code::KEY_HANGEUL => todo!(),
            Code::KEY_HANGUEL => todo!(),
            Code::KEY_HANJA => todo!(),
            Code::KEY_YEN => todo!(),
            Code::KEY_LEFTMETA => todo!(),
            Code::KEY_RIGHTMETA => todo!(),
            Code::KEY_COMPOSE => todo!(),
            Code::KEY_STOP => todo!(),
            Code::KEY_AGAIN => todo!(),
            Code::KEY_PROPS => todo!(),
            Code::KEY_UNDO => todo!(),
            Code::KEY_FRONT => todo!(),
            Code::KEY_COPY => todo!(),
            Code::KEY_OPEN => todo!(),
            Code::KEY_PASTE => todo!(),
            Code::KEY_FIND => todo!(),
            Code::KEY_CUT => todo!(),
            Code::KEY_HELP => todo!(),
            Code::KEY_MENU => todo!(),
            Code::KEY_CALC => todo!(),
            Code::KEY_SETUP => todo!(),
            Code::KEY_SLEEP => todo!(),
            Code::KEY_WAKEUP => todo!(),
            Code::KEY_FILE => todo!(),
            Code::KEY_SENDFILE => todo!(),
            Code::KEY_DELETEFILE => todo!(),
            Code::KEY_XFER => todo!(),
            Code::KEY_PROG1 => todo!(),
            Code::KEY_PROG2 => todo!(),
            Code::KEY_WWW => todo!(),
            Code::KEY_MSDOS => todo!(),
            Code::KEY_COFFEE => todo!(),
            Code::KEY_SCREENLOCK => todo!(),
            Code::KEY_ROTATE_DISPLAY => todo!(),
            Code::KEY_DIRECTION => todo!(),
            Code::KEY_CYCLEWINDOWS => todo!(),
            Code::KEY_MAIL => todo!(),
            Code::KEY_BOOKMARKS => todo!(),
            Code::KEY_COMPUTER => todo!(),
            Code::KEY_BACK => todo!(),
            Code::KEY_FORWARD => todo!(),
            Code::KEY_CLOSECD => todo!(),
            Code::KEY_EJECTCD => todo!(),
            Code::KEY_EJECTCLOSECD => todo!(),
            Code::KEY_NEXTSONG => todo!(),
            Code::KEY_PLAYPAUSE => todo!(),
            Code::KEY_PREVIOUSSONG => todo!(),
            Code::KEY_STOPCD => todo!(),
            Code::KEY_RECORD => todo!(),
            Code::KEY_REWIND => todo!(),
            Code::KEY_PHONE => todo!(),
            Code::KEY_ISO => todo!(),
            Code::KEY_CONFIG => todo!(),
            Code::KEY_HOMEPAGE => todo!(),
            Code::KEY_REFRESH => todo!(),
            Code::KEY_EXIT => todo!(),
            Code::KEY_MOVE => todo!(),
            Code::KEY_EDIT => todo!(),
            Code::KEY_SCROLLUP => todo!(),
            Code::KEY_SCROLLDOWN => todo!(),
            Code::KEY_KPLEFTPAREN => todo!(),
            Code::KEY_KPRIGHTPAREN => todo!(),
            Code::KEY_NEW => todo!(),
            Code::KEY_REDO => todo!(),
            Code::KEY_F13 => todo!(),
            Code::KEY_F14 => todo!(),
            Code::KEY_F15 => todo!(),
            Code::KEY_F16 => todo!(),
            Code::KEY_F17 => todo!(),
            Code::KEY_F18 => todo!(),
            Code::KEY_F19 => todo!(),
            Code::KEY_F20 => todo!(),
            Code::KEY_F21 => todo!(),
            Code::KEY_F22 => todo!(),
            Code::KEY_F23 => todo!(),
            Code::KEY_F24 => todo!(),
            Code::KEY_PLAYCD => todo!(),
            Code::KEY_PAUSECD => todo!(),
            Code::KEY_PROG3 => todo!(),
            Code::KEY_PROG4 => todo!(),
            Code::KEY_ALL_APPLICATIONS => todo!(),
            Code::KEY_DASHBOARD => todo!(),
            Code::KEY_SUSPEND => todo!(),
            Code::KEY_CLOSE => todo!(),
            Code::KEY_PLAY => todo!(),
            Code::KEY_FASTFORWARD => todo!(),
            Code::KEY_BASSBOOST => todo!(),
            Code::KEY_PRINT => todo!(),
            Code::KEY_HP => todo!(),
            Code::KEY_CAMERA => todo!(),
            Code::KEY_SOUND => todo!(),
            Code::KEY_QUESTION => todo!(),
            Code::KEY_EMAIL => todo!(),
            Code::KEY_CHAT => todo!(),
            Code::KEY_SEARCH => todo!(),
            Code::KEY_CONNECT => todo!(),
            Code::KEY_FINANCE => todo!(),
            Code::KEY_SPORT => todo!(),
            Code::KEY_SHOP => todo!(),
            Code::KEY_ALTERASE => todo!(),
            Code::KEY_CANCEL => todo!(),
            Code::KEY_BRIGHTNESSDOWN => todo!(),
            Code::KEY_BRIGHTNESSUP => todo!(),
            Code::KEY_MEDIA => todo!(),
            Code::KEY_SWITCHVIDEOMODE => todo!(),
            Code::KEY_KBDILLUMTOGGLE => todo!(),
            Code::KEY_KBDILLUMDOWN => todo!(),
            Code::KEY_KBDILLUMUP => todo!(),
            Code::KEY_SEND => todo!(),
            Code::KEY_REPLY => todo!(),
            Code::KEY_FORWARDMAIL => todo!(),
            Code::KEY_SAVE => todo!(),
            Code::KEY_DOCUMENTS => todo!(),
            Code::KEY_BATTERY => todo!(),
            Code::KEY_BLUETOOTH => todo!(),
            Code::KEY_WLAN => todo!(),
            Code::KEY_UWB => todo!(),
            Code::KEY_UNKNOWN => todo!(),
            Code::KEY_VIDEO_NEXT => todo!(),
            Code::KEY_VIDEO_PREV => todo!(),
            Code::KEY_BRIGHTNESS_CYCLE => todo!(),
            Code::KEY_BRIGHTNESS_AUTO => todo!(),
            Code::KEY_BRIGHTNESS_ZERO => todo!(),
            Code::KEY_DISPLAY_OFF => todo!(),
            Code::KEY_WWAN => todo!(),
            Code::KEY_WIMAX => todo!(),
            Code::KEY_RFKILL => todo!(),
            Code::KEY_MICMUTE => todo!(),
        };
        write!(f, "{}", key)
    }
}
