#[allow(non_camel_case_types, dead_code)]
#[derive(Debug, PartialEq)]
pub enum Code {
    KEY_RESERVED,
    KEY_ESC,
    KEY_1,
    KEY_2,
    KEY_3,
    KEY_4,
    KEY_5,
    KEY_6,
    KEY_7,
    KEY_8,
    KEY_9,
    KEY_0,
    KEY_MINUS,
    KEY_EQUAL,
    KEY_BACKSPACE,
    KEY_TAB,
    KEY_Q,
    KEY_W,
    KEY_E,
    KEY_R,
    KEY_T,
    KEY_Y,
    KEY_U,
    KEY_I,
    KEY_O,
    KEY_P,
    KEY_LEFTBRACE,
    KEY_RIGHTBRACE,
    KEY_ENTER,
    KEY_LEFTCTRL,
    KEY_A,
    KEY_S,
    KEY_D,
    KEY_F,
    KEY_G,
    KEY_H,
    KEY_J,
    KEY_K,
    KEY_L,
    KEY_SEMICOLON,
    KEY_APOSTROPHE,
    KEY_GRAVE,
    KEY_LEFTSHIFT,
    KEY_BACKSLASH,
    KEY_Z,
    KEY_X,
    KEY_C,
    KEY_V,
    KEY_B,
    KEY_N,
    KEY_M,
    KEY_COMMA,
    KEY_DOT,
    KEY_SLASH,
    KEY_RIGHTSHIFT,
    KEY_KPASTERISK,
    KEY_LEFTALT,
    KEY_SPACE,
    KEY_CAPSLOCK,
    KEY_F1,
    KEY_F2,
    KEY_F3,
    KEY_F4,
    KEY_F5,
    KEY_F6,
    KEY_F7,
    KEY_F8,
    KEY_F9,
    KEY_F10,
    KEY_NUMLOCK,
    KEY_SCROLLLOCK,
    KEY_KP7,
    KEY_KP8,
    KEY_KP9,
    KEY_KPMINUS,
    KEY_KP4,
    KEY_KP5,
    KEY_KP6,
    KEY_KPPLUS,
    KEY_KP1,
    KEY_KP2,
    KEY_KP3,
    KEY_KP0,
    KEY_KPDOT,

    KEY_ZENKAKUHANKAKU,
    KEY_102ND,
    KEY_F11,
    KEY_F12,
    KEY_RO,
    KEY_KATAKANA,
    KEY_HIRAGANA,
    KEY_HENKAN,
    KEY_KATAKANAHIRAGANA,
    KEY_MUHENKAN,
    KEY_KPJPCOMMA,
    KEY_KPENTER,
    KEY_RIGHTCTRL,
    KEY_KPSLASH,
    KEY_SYSRQ,
    KEY_RIGHTALT,
    KEY_LINEFEED,
    KEY_HOME,
    KEY_UP,
    KEY_PAGEUP,
    KEY_LEFT,
    KEY_RIGHT,
    KEY_END,
    KEY_DOWN,
    KEY_PAGEDOWN,
    KEY_INSERT,
    KEY_DELETE,
    KEY_MACRO,
    KEY_MUTE,
    KEY_VOLUMEDOWN,
    KEY_VOLUMEUP,
    KEY_POWER, /* SC System Power Down */
    KEY_KPEQUAL,
    KEY_KPPLUSMINUS,
    KEY_PAUSE,
    KEY_SCALE, /* AL Compiz Scale (Expose) */

    KEY_KPCOMMA,
    KEY_HANGEUL,
    KEY_HANGUEL, // FIXME: same value as KEY_HANGEUL
    KEY_HANJA,
    KEY_YEN,
    KEY_LEFTMETA,
    KEY_RIGHTMETA,
    KEY_COMPOSE,

    KEY_STOP, /* AC Stop */
    KEY_AGAIN,
    KEY_PROPS, /* AC Properties */
    KEY_UNDO,  /* AC Undo */
    KEY_FRONT,
    KEY_COPY,  /* AC Copy */
    KEY_OPEN,  /* AC Open */
    KEY_PASTE, /* AC Paste */
    KEY_FIND,  /* AC Search */
    KEY_CUT,   /* AC Cut */
    KEY_HELP,  /* AL Integrated Help Center */
    KEY_MENU,  /* Menu (show menu) */
    KEY_CALC,  /* AL Calculator */
    KEY_SETUP,
    KEY_SLEEP,  /* SC System Sleep */
    KEY_WAKEUP, /* System Wake Up */
    KEY_FILE,   /* AL Local Machine Browser */
    KEY_SENDFILE,
    KEY_DELETEFILE,
    KEY_XFER,
    KEY_PROG1,
    KEY_PROG2,
    KEY_WWW, /* AL Internet Browser */
    KEY_MSDOS,
    KEY_COFFEE,         /* AL Terminal Lock/Screensaver */
    KEY_SCREENLOCK,     //FIXME: same as KEY_COFFEE
    KEY_ROTATE_DISPLAY, /* Display orientation for e.g. tablets */
    KEY_DIRECTION,      // FIXME: same as KEY_ROTATE_DISPLAY
    KEY_CYCLEWINDOWS,
    KEY_MAIL,
    KEY_BOOKMARKS, /* AC Bookmarks */
    KEY_COMPUTER,
    KEY_BACK,    /* AC Back */
    KEY_FORWARD, /* AC Forward */
    KEY_CLOSECD,
    KEY_EJECTCD,
    KEY_EJECTCLOSECD,
    KEY_NEXTSONG,
    KEY_PLAYPAUSE,
    KEY_PREVIOUSSONG,
    KEY_STOPCD,
    KEY_RECORD,
    KEY_REWIND,
    KEY_PHONE, /* Media Select Telephone */
    KEY_ISO,
    KEY_CONFIG,   /* AL Consumer Control Configuration */
    KEY_HOMEPAGE, /* AC Home */
    KEY_REFRESH,  /* AC Refresh */
    KEY_EXIT,     /* AC Exit */
    KEY_MOVE,
    KEY_EDIT,
    KEY_SCROLLUP,
    KEY_SCROLLDOWN,
    KEY_KPLEFTPAREN,
    KEY_KPRIGHTPAREN,
    KEY_NEW,  /* AC New */
    KEY_REDO, /* AC Redo/Repeat */

    KEY_F13,
    KEY_F14,
    KEY_F15,
    KEY_F16,
    KEY_F17,
    KEY_F18,
    KEY_F19,
    KEY_F20,
    KEY_F21,
    KEY_F22,
    KEY_F23,
    KEY_F24,

    KEY_PLAYCD,
    KEY_PAUSECD,
    KEY_PROG3,
    KEY_PROG4,
    KEY_ALL_APPLICATIONS, /* AC Desktop Show All Applications */
    KEY_DASHBOARD,        // FIXME: same as KEY_ALL_APPLICATIONS
    KEY_SUSPEND,
    KEY_CLOSE, /* AC Close */
    KEY_PLAY,
    KEY_FASTFORWARD,
    KEY_BASSBOOST,
    KEY_PRINT, /* AC Print */
    KEY_HP,
    KEY_CAMERA,
    KEY_SOUND,
    KEY_QUESTION,
    KEY_EMAIL,
    KEY_CHAT,
    KEY_SEARCH,
    KEY_CONNECT,
    KEY_FINANCE, /* AL Checkbook/Finance */
    KEY_SPORT,
    KEY_SHOP,
    KEY_ALTERASE,
    KEY_CANCEL, /* AC Cancel */
    KEY_BRIGHTNESSDOWN,
    KEY_BRIGHTNESSUP,
    KEY_MEDIA,

    KEY_SWITCHVIDEOMODE, /* Cycle between available video outputs (Monitor/LCD/TV-out/etc) */
    KEY_KBDILLUMTOGGLE,
    KEY_KBDILLUMDOWN,
    KEY_KBDILLUMUP,

    KEY_SEND,        /* AC Send */
    KEY_REPLY,       /* AC Reply */
    KEY_FORWARDMAIL, /* AC Forward Msg */
    KEY_SAVE,        /* AC Save */
    KEY_DOCUMENTS,

    KEY_BATTERY,

    KEY_BLUETOOTH,
    KEY_WLAN,
    KEY_UWB,

    KEY_UNKNOWN,

    KEY_VIDEO_NEXT,       /* drive next video source */
    KEY_VIDEO_PREV,       /* drive previous video source */
    KEY_BRIGHTNESS_CYCLE, /* brightness up, after max is min */
    KEY_BRIGHTNESS_AUTO, /* Set Auto Brightness: manual brightness control is off, rely on ambient */
    KEY_BRIGHTNESS_ZERO, // FIXME: same as KEY_BRIGHTNESS_AUTO
    KEY_DISPLAY_OFF,     /* display device to off state */

    KEY_WWAN,   /* Wireless WAN (LTE, UMTS, GSM, etc.) */
    KEY_WIMAX,  //FIXME: same as KEY_WWAN
    KEY_RFKILL, /* Key that controls all radios */

    KEY_MICMUTE, /* Mute / unmute the microphone */
}

#[derive(Debug)]
pub enum KeyError {
    UnknownCode,
}

impl TryFrom<u16> for Code {
    type Error = KeyError;

    fn try_from(value: u16) -> Result<Self, Self::Error> {
        match value {
            0 => Ok(Self::KEY_RESERVED),
            1 => Ok(Self::KEY_ESC),
            2 => Ok(Self::KEY_1),
            3 => Ok(Self::KEY_2),
            4 => Ok(Self::KEY_3),
            5 => Ok(Self::KEY_4),
            6 => Ok(Self::KEY_5),
            7 => Ok(Self::KEY_6),
            8 => Ok(Self::KEY_7),
            9 => Ok(Self::KEY_8),
            10 => Ok(Self::KEY_9),
            11 => Ok(Self::KEY_0),
            12 => Ok(Self::KEY_MINUS),
            13 => Ok(Self::KEY_EQUAL),
            14 => Ok(Self::KEY_BACKSPACE),
            15 => Ok(Self::KEY_TAB),
            16 => Ok(Self::KEY_Q),
            17 => Ok(Self::KEY_W),
            18 => Ok(Self::KEY_E),
            19 => Ok(Self::KEY_R),
            20 => Ok(Self::KEY_T),
            21 => Ok(Self::KEY_Y),
            22 => Ok(Self::KEY_U),
            23 => Ok(Self::KEY_I),
            24 => Ok(Self::KEY_O),
            25 => Ok(Self::KEY_P),
            26 => Ok(Self::KEY_LEFTBRACE),
            27 => Ok(Self::KEY_RIGHTBRACE),
            28 => Ok(Self::KEY_ENTER),
            29 => Ok(Self::KEY_LEFTCTRL),
            30 => Ok(Self::KEY_A),
            31 => Ok(Self::KEY_S),
            32 => Ok(Self::KEY_D),
            33 => Ok(Self::KEY_F),
            34 => Ok(Self::KEY_G),
            35 => Ok(Self::KEY_H),
            36 => Ok(Self::KEY_J),
            37 => Ok(Self::KEY_K),
            38 => Ok(Self::KEY_L),
            39 => Ok(Self::KEY_SEMICOLON),
            40 => Ok(Self::KEY_APOSTROPHE),
            41 => Ok(Self::KEY_GRAVE),
            42 => Ok(Self::KEY_LEFTSHIFT),
            43 => Ok(Self::KEY_BACKSLASH),
            44 => Ok(Self::KEY_Z),
            45 => Ok(Self::KEY_X),
            46 => Ok(Self::KEY_C),
            47 => Ok(Self::KEY_V),
            48 => Ok(Self::KEY_B),
            49 => Ok(Self::KEY_N),
            50 => Ok(Self::KEY_M),
            51 => Ok(Self::KEY_COMMA),
            52 => Ok(Self::KEY_DOT),
            53 => Ok(Self::KEY_SLASH),
            54 => Ok(Self::KEY_RIGHTSHIFT),
            55 => Ok(Self::KEY_KPASTERISK),
            56 => Ok(Self::KEY_LEFTALT),
            57 => Ok(Self::KEY_SPACE),
            58 => Ok(Self::KEY_CAPSLOCK),
            59 => Ok(Self::KEY_F1),
            60 => Ok(Self::KEY_F2),
            61 => Ok(Self::KEY_F3),
            62 => Ok(Self::KEY_F4),
            63 => Ok(Self::KEY_F5),
            64 => Ok(Self::KEY_F6),
            65 => Ok(Self::KEY_F7),
            66 => Ok(Self::KEY_F8),
            67 => Ok(Self::KEY_F9),
            68 => Ok(Self::KEY_F10),
            69 => Ok(Self::KEY_NUMLOCK),
            70 => Ok(Self::KEY_SCROLLLOCK),
            71 => Ok(Self::KEY_KP7),
            72 => Ok(Self::KEY_KP8),
            73 => Ok(Self::KEY_KP9),
            74 => Ok(Self::KEY_KPMINUS),
            75 => Ok(Self::KEY_KP4),
            76 => Ok(Self::KEY_KP5),
            77 => Ok(Self::KEY_KP6),
            78 => Ok(Self::KEY_KPPLUS),
            79 => Ok(Self::KEY_KP1),
            80 => Ok(Self::KEY_KP2),
            81 => Ok(Self::KEY_KP3),
            82 => Ok(Self::KEY_KP0),
            83 => Ok(Self::KEY_KPDOT),
            85 => Ok(Self::KEY_ZENKAKUHANKAKU),
            86 => Ok(Self::KEY_102ND),
            87 => Ok(Self::KEY_F11),
            88 => Ok(Self::KEY_F12),
            89 => Ok(Self::KEY_RO),
            90 => Ok(Self::KEY_KATAKANA),
            91 => Ok(Self::KEY_HIRAGANA),
            92 => Ok(Self::KEY_HENKAN),
            93 => Ok(Self::KEY_KATAKANAHIRAGANA),
            94 => Ok(Self::KEY_MUHENKAN),
            95 => Ok(Self::KEY_KPJPCOMMA),
            96 => Ok(Self::KEY_KPENTER),
            97 => Ok(Self::KEY_RIGHTCTRL),
            98 => Ok(Self::KEY_KPSLASH),
            99 => Ok(Self::KEY_SYSRQ),
            100 => Ok(Self::KEY_RIGHTALT),
            101 => Ok(Self::KEY_LINEFEED),
            102 => Ok(Self::KEY_HOME),
            103 => Ok(Self::KEY_UP),
            104 => Ok(Self::KEY_PAGEUP),
            105 => Ok(Self::KEY_LEFT),
            106 => Ok(Self::KEY_RIGHT),
            107 => Ok(Self::KEY_END),
            108 => Ok(Self::KEY_DOWN),
            109 => Ok(Self::KEY_PAGEDOWN),
            110 => Ok(Self::KEY_INSERT),
            111 => Ok(Self::KEY_DELETE),
            112 => Ok(Self::KEY_MACRO),
            113 => Ok(Self::KEY_MUTE),
            114 => Ok(Self::KEY_VOLUMEDOWN),
            115 => Ok(Self::KEY_VOLUMEUP),
            116 => Ok(Self::KEY_POWER),
            117 => Ok(Self::KEY_KPEQUAL),
            118 => Ok(Self::KEY_KPPLUSMINUS),
            119 => Ok(Self::KEY_PAUSE),
            120 => Ok(Self::KEY_SCALE),
            121 => Ok(Self::KEY_KPCOMMA),
            122 => Ok(Self::KEY_HANGEUL),
            123 => Ok(Self::KEY_HANJA),
            124 => Ok(Self::KEY_YEN),
            125 => Ok(Self::KEY_LEFTMETA),
            126 => Ok(Self::KEY_RIGHTMETA),
            127 => Ok(Self::KEY_COMPOSE),
            128 => Ok(Self::KEY_STOP),
            129 => Ok(Self::KEY_AGAIN),
            130 => Ok(Self::KEY_PROPS),
            131 => Ok(Self::KEY_UNDO),
            132 => Ok(Self::KEY_FRONT),
            133 => Ok(Self::KEY_COPY),
            134 => Ok(Self::KEY_OPEN),
            135 => Ok(Self::KEY_PASTE),
            136 => Ok(Self::KEY_FIND),
            137 => Ok(Self::KEY_CUT),
            138 => Ok(Self::KEY_HELP),
            139 => Ok(Self::KEY_MENU),
            140 => Ok(Self::KEY_CALC),
            141 => Ok(Self::KEY_SETUP),
            142 => Ok(Self::KEY_SLEEP),
            143 => Ok(Self::KEY_WAKEUP),
            144 => Ok(Self::KEY_FILE),
            145 => Ok(Self::KEY_SENDFILE),
            146 => Ok(Self::KEY_DELETEFILE),
            147 => Ok(Self::KEY_XFER),
            148 => Ok(Self::KEY_PROG1),
            149 => Ok(Self::KEY_PROG2),
            150 => Ok(Self::KEY_WWW),
            151 => Ok(Self::KEY_MSDOS),
            152 => Ok(Self::KEY_COFFEE),
            153 => Ok(Self::KEY_ROTATE_DISPLAY),
            154 => Ok(Self::KEY_CYCLEWINDOWS),
            155 => Ok(Self::KEY_MAIL),
            156 => Ok(Self::KEY_BOOKMARKS),
            157 => Ok(Self::KEY_COMPUTER),
            158 => Ok(Self::KEY_BACK),
            159 => Ok(Self::KEY_FORWARD),
            160 => Ok(Self::KEY_CLOSECD),
            161 => Ok(Self::KEY_EJECTCD),
            162 => Ok(Self::KEY_EJECTCLOSECD),
            163 => Ok(Self::KEY_NEXTSONG),
            164 => Ok(Self::KEY_PLAYPAUSE),
            165 => Ok(Self::KEY_PREVIOUSSONG),
            166 => Ok(Self::KEY_STOPCD),
            167 => Ok(Self::KEY_RECORD),
            168 => Ok(Self::KEY_REWIND),
            169 => Ok(Self::KEY_PHONE),
            170 => Ok(Self::KEY_ISO),
            171 => Ok(Self::KEY_CONFIG),
            172 => Ok(Self::KEY_HOMEPAGE),
            173 => Ok(Self::KEY_REFRESH),
            174 => Ok(Self::KEY_EXIT),
            175 => Ok(Self::KEY_MOVE),
            176 => Ok(Self::KEY_EDIT),
            177 => Ok(Self::KEY_SCROLLUP),
            178 => Ok(Self::KEY_SCROLLDOWN),
            179 => Ok(Self::KEY_KPLEFTPAREN),
            180 => Ok(Self::KEY_KPRIGHTPAREN),
            181 => Ok(Self::KEY_NEW),
            182 => Ok(Self::KEY_REDO),
            183 => Ok(Self::KEY_F13),
            184 => Ok(Self::KEY_F14),
            185 => Ok(Self::KEY_F15),
            186 => Ok(Self::KEY_F16),
            187 => Ok(Self::KEY_F17),
            188 => Ok(Self::KEY_F18),
            189 => Ok(Self::KEY_F19),
            190 => Ok(Self::KEY_F20),
            191 => Ok(Self::KEY_F21),
            192 => Ok(Self::KEY_F22),
            193 => Ok(Self::KEY_F23),
            194 => Ok(Self::KEY_F24),
            200 => Ok(Self::KEY_PLAYCD),
            201 => Ok(Self::KEY_PAUSECD),
            202 => Ok(Self::KEY_PROG3),
            203 => Ok(Self::KEY_PROG4),
            204 => Ok(Self::KEY_ALL_APPLICATIONS),
            205 => Ok(Self::KEY_SUSPEND),
            206 => Ok(Self::KEY_CLOSE),
            207 => Ok(Self::KEY_PLAY),
            208 => Ok(Self::KEY_FASTFORWARD),
            209 => Ok(Self::KEY_BASSBOOST),
            210 => Ok(Self::KEY_PRINT),
            211 => Ok(Self::KEY_HP),
            212 => Ok(Self::KEY_CAMERA),
            213 => Ok(Self::KEY_SOUND),
            214 => Ok(Self::KEY_QUESTION),
            215 => Ok(Self::KEY_EMAIL),
            216 => Ok(Self::KEY_CHAT),
            217 => Ok(Self::KEY_SEARCH),
            218 => Ok(Self::KEY_CONNECT),
            219 => Ok(Self::KEY_FINANCE),
            220 => Ok(Self::KEY_SPORT),
            221 => Ok(Self::KEY_SHOP),
            222 => Ok(Self::KEY_ALTERASE),
            223 => Ok(Self::KEY_CANCEL),
            224 => Ok(Self::KEY_BRIGHTNESSDOWN),
            225 => Ok(Self::KEY_BRIGHTNESSUP),
            226 => Ok(Self::KEY_MEDIA),
            227 => Ok(Self::KEY_SWITCHVIDEOMODE),
            228 => Ok(Self::KEY_KBDILLUMTOGGLE),
            229 => Ok(Self::KEY_KBDILLUMDOWN),
            230 => Ok(Self::KEY_KBDILLUMUP),
            231 => Ok(Self::KEY_SEND),
            232 => Ok(Self::KEY_REPLY),
            233 => Ok(Self::KEY_FORWARDMAIL),
            234 => Ok(Self::KEY_SAVE),
            235 => Ok(Self::KEY_DOCUMENTS),
            236 => Ok(Self::KEY_BATTERY),
            237 => Ok(Self::KEY_BLUETOOTH),
            238 => Ok(Self::KEY_WLAN),
            239 => Ok(Self::KEY_UWB),
            240 => Ok(Self::KEY_UNKNOWN),
            241 => Ok(Self::KEY_VIDEO_NEXT),
            242 => Ok(Self::KEY_VIDEO_PREV),
            243 => Ok(Self::KEY_BRIGHTNESS_CYCLE),
            244 => Ok(Self::KEY_BRIGHTNESS_AUTO),
            245 => Ok(Self::KEY_DISPLAY_OFF),
            246 => Ok(Self::KEY_WWAN),
            247 => Ok(Self::KEY_RFKILL),
            248 => Ok(Self::KEY_MICMUTE),
            _ => Err(self::KeyError::UnknownCode),
        }
    }
}

impl ToString for Code {
    fn to_string(&self) -> String {
        match self {
            Code::KEY_RESERVED => "<reserved>",
            Code::KEY_ESC => "<escapte>",
            Code::KEY_1 => "1",
            Code::KEY_2 => "2",
            Code::KEY_3 => "3",
            Code::KEY_4 => "4",
            Code::KEY_5 => "5",
            Code::KEY_6 => "6",
            Code::KEY_7 => "7",
            Code::KEY_8 => "8",
            Code::KEY_9 => "9",
            Code::KEY_0 => "0",
            Code::KEY_MINUS => "-",
            Code::KEY_EQUAL => "=",
            Code::KEY_BACKSPACE => "<del>",
            Code::KEY_TAB => "  ",
            Code::KEY_Q => "q",
            Code::KEY_W => "w",
            Code::KEY_E => "e",
            Code::KEY_R => "r",
            Code::KEY_T => "t",
            Code::KEY_Y => "y",
            Code::KEY_U => "u",
            Code::KEY_I => "i",
            Code::KEY_O => "o",
            Code::KEY_P => "p",
            Code::KEY_LEFTBRACE => todo!(),
            Code::KEY_RIGHTBRACE => todo!(),
            Code::KEY_ENTER => "<enter>",
            Code::KEY_LEFTCTRL => "<lctrl>",
            Code::KEY_A => "a",
            Code::KEY_S => "s",
            Code::KEY_D => "d",
            Code::KEY_F => "f",
            Code::KEY_G => "g",
            Code::KEY_H => "h",
            Code::KEY_J => "j",
            Code::KEY_K => "k",
            Code::KEY_L => "l",
            Code::KEY_SEMICOLON => todo!(),
            Code::KEY_APOSTROPHE => todo!(),
            Code::KEY_GRAVE => todo!(),
            Code::KEY_LEFTSHIFT => "<lshift>",
            Code::KEY_BACKSLASH => todo!(),
            Code::KEY_Z => "z",
            Code::KEY_X => "x",
            Code::KEY_C => "c",
            Code::KEY_V => "v",
            Code::KEY_B => "b",
            Code::KEY_N => "n",
            Code::KEY_M => "m",
            Code::KEY_COMMA => todo!(),
            Code::KEY_DOT => todo!(),
            Code::KEY_SLASH => todo!(),
            Code::KEY_RIGHTSHIFT => "<rshift>",
            Code::KEY_KPASTERISK => todo!(),
            Code::KEY_LEFTALT => todo!(),
            Code::KEY_SPACE => " ",
            Code::KEY_CAPSLOCK => todo!(),
            Code::KEY_F1 => "F1",
            Code::KEY_F2 => "F2",
            Code::KEY_F3 => "F3",
            Code::KEY_F4 => "F4",
            Code::KEY_F5 => "F5",
            Code::KEY_F6 => "F6",
            Code::KEY_F7 => "F7",
            Code::KEY_F8 => "F8",
            Code::KEY_F9 => "F9",
            Code::KEY_F10 => "F10",
            Code::KEY_NUMLOCK => "<numlock>",
            Code::KEY_SCROLLLOCK => todo!(),
            Code::KEY_KP7 => "7",
            Code::KEY_KP8 => "8",
            Code::KEY_KP9 => "9",
            Code::KEY_KPMINUS => "-",
            Code::KEY_KP4 => "4",
            Code::KEY_KP5 => "5",
            Code::KEY_KP6 => "6",
            Code::KEY_KPPLUS => "+",
            Code::KEY_KP1 => "1",
            Code::KEY_KP2 => "2",
            Code::KEY_KP3 => "3",
            Code::KEY_KP0 => "0",
            Code::KEY_KPDOT => ".",
            Code::KEY_ZENKAKUHANKAKU => todo!(),
            Code::KEY_102ND => todo!(),
            Code::KEY_F11 => todo!(),
            Code::KEY_F12 => todo!(),
            Code::KEY_RO => todo!(),
            Code::KEY_KATAKANA => todo!(),
            Code::KEY_HIRAGANA => todo!(),
            Code::KEY_HENKAN => todo!(),
            Code::KEY_KATAKANAHIRAGANA => todo!(),
            Code::KEY_MUHENKAN => todo!(),
            Code::KEY_KPJPCOMMA => todo!(),
            Code::KEY_KPENTER => todo!(),
            Code::KEY_RIGHTCTRL => "<rctrl>",
            Code::KEY_KPSLASH => todo!(),
            Code::KEY_SYSRQ => todo!(),
            Code::KEY_RIGHTALT => todo!(),
            Code::KEY_LINEFEED => todo!(),
            Code::KEY_HOME => todo!(),
            Code::KEY_UP => todo!(),
            Code::KEY_PAGEUP => todo!(),
            Code::KEY_LEFT => todo!(),
            Code::KEY_RIGHT => todo!(),
            Code::KEY_END => todo!(),
            Code::KEY_DOWN => todo!(),
            Code::KEY_PAGEDOWN => todo!(),
            Code::KEY_INSERT => todo!(),
            Code::KEY_DELETE => todo!(),
            Code::KEY_MACRO => todo!(),
            Code::KEY_MUTE => todo!(),
            Code::KEY_VOLUMEDOWN => todo!(),
            Code::KEY_VOLUMEUP => todo!(),
            Code::KEY_POWER => todo!(),
            Code::KEY_KPEQUAL => todo!(),
            Code::KEY_KPPLUSMINUS => todo!(),
            Code::KEY_PAUSE => todo!(),
            Code::KEY_SCALE => todo!(),
            Code::KEY_KPCOMMA => todo!(),
            Code::KEY_HANGEUL => todo!(),
            Code::KEY_HANGUEL => todo!(),
            Code::KEY_HANJA => todo!(),
            Code::KEY_YEN => todo!(),
            Code::KEY_LEFTMETA => todo!(),
            Code::KEY_RIGHTMETA => todo!(),
            Code::KEY_COMPOSE => todo!(),
            Code::KEY_STOP => todo!(),
            Code::KEY_AGAIN => todo!(),
            Code::KEY_PROPS => todo!(),
            Code::KEY_UNDO => todo!(),
            Code::KEY_FRONT => todo!(),
            Code::KEY_COPY => todo!(),
            Code::KEY_OPEN => todo!(),
            Code::KEY_PASTE => todo!(),
            Code::KEY_FIND => todo!(),
            Code::KEY_CUT => todo!(),
            Code::KEY_HELP => todo!(),
            Code::KEY_MENU => todo!(),
            Code::KEY_CALC => todo!(),
            Code::KEY_SETUP => todo!(),
            Code::KEY_SLEEP => todo!(),
            Code::KEY_WAKEUP => todo!(),
            Code::KEY_FILE => todo!(),
            Code::KEY_SENDFILE => todo!(),
            Code::KEY_DELETEFILE => todo!(),
            Code::KEY_XFER => todo!(),
            Code::KEY_PROG1 => todo!(),
            Code::KEY_PROG2 => todo!(),
            Code::KEY_WWW => todo!(),
            Code::KEY_MSDOS => todo!(),
            Code::KEY_COFFEE => todo!(),
            Code::KEY_SCREENLOCK => todo!(),
            Code::KEY_ROTATE_DISPLAY => todo!(),
            Code::KEY_DIRECTION => todo!(),
            Code::KEY_CYCLEWINDOWS => todo!(),
            Code::KEY_MAIL => todo!(),
            Code::KEY_BOOKMARKS => todo!(),
            Code::KEY_COMPUTER => todo!(),
            Code::KEY_BACK => todo!(),
            Code::KEY_FORWARD => todo!(),
            Code::KEY_CLOSECD => todo!(),
            Code::KEY_EJECTCD => todo!(),
            Code::KEY_EJECTCLOSECD => todo!(),
            Code::KEY_NEXTSONG => todo!(),
            Code::KEY_PLAYPAUSE => todo!(),
            Code::KEY_PREVIOUSSONG => todo!(),
            Code::KEY_STOPCD => todo!(),
            Code::KEY_RECORD => todo!(),
            Code::KEY_REWIND => todo!(),
            Code::KEY_PHONE => todo!(),
            Code::KEY_ISO => todo!(),
            Code::KEY_CONFIG => todo!(),
            Code::KEY_HOMEPAGE => todo!(),
            Code::KEY_REFRESH => todo!(),
            Code::KEY_EXIT => todo!(),
            Code::KEY_MOVE => todo!(),
            Code::KEY_EDIT => todo!(),
            Code::KEY_SCROLLUP => todo!(),
            Code::KEY_SCROLLDOWN => todo!(),
            Code::KEY_KPLEFTPAREN => todo!(),
            Code::KEY_KPRIGHTPAREN => todo!(),
            Code::KEY_NEW => todo!(),
            Code::KEY_REDO => todo!(),
            Code::KEY_F13 => todo!(),
            Code::KEY_F14 => todo!(),
            Code::KEY_F15 => todo!(),
            Code::KEY_F16 => todo!(),
            Code::KEY_F17 => todo!(),
            Code::KEY_F18 => todo!(),
            Code::KEY_F19 => todo!(),
            Code::KEY_F20 => todo!(),
            Code::KEY_F21 => todo!(),
            Code::KEY_F22 => todo!(),
            Code::KEY_F23 => todo!(),
            Code::KEY_F24 => todo!(),
            Code::KEY_PLAYCD => todo!(),
            Code::KEY_PAUSECD => todo!(),
            Code::KEY_PROG3 => todo!(),
            Code::KEY_PROG4 => todo!(),
            Code::KEY_ALL_APPLICATIONS => todo!(),
            Code::KEY_DASHBOARD => todo!(),
            Code::KEY_SUSPEND => todo!(),
            Code::KEY_CLOSE => todo!(),
            Code::KEY_PLAY => todo!(),
            Code::KEY_FASTFORWARD => todo!(),
            Code::KEY_BASSBOOST => todo!(),
            Code::KEY_PRINT => todo!(),
            Code::KEY_HP => todo!(),
            Code::KEY_CAMERA => todo!(),
            Code::KEY_SOUND => todo!(),
            Code::KEY_QUESTION => todo!(),
            Code::KEY_EMAIL => todo!(),
            Code::KEY_CHAT => todo!(),
            Code::KEY_SEARCH => todo!(),
            Code::KEY_CONNECT => todo!(),
            Code::KEY_FINANCE => todo!(),
            Code::KEY_SPORT => todo!(),
            Code::KEY_SHOP => todo!(),
            Code::KEY_ALTERASE => todo!(),
            Code::KEY_CANCEL => todo!(),
            Code::KEY_BRIGHTNESSDOWN => todo!(),
            Code::KEY_BRIGHTNESSUP => todo!(),
            Code::KEY_MEDIA => todo!(),
            Code::KEY_SWITCHVIDEOMODE => todo!(),
            Code::KEY_KBDILLUMTOGGLE => todo!(),
            Code::KEY_KBDILLUMDOWN => todo!(),
            Code::KEY_KBDILLUMUP => todo!(),
            Code::KEY_SEND => todo!(),
            Code::KEY_REPLY => todo!(),
            Code::KEY_FORWARDMAIL => todo!(),
            Code::KEY_SAVE => todo!(),
            Code::KEY_DOCUMENTS => todo!(),
            Code::KEY_BATTERY => todo!(),
            Code::KEY_BLUETOOTH => todo!(),
            Code::KEY_WLAN => todo!(),
            Code::KEY_UWB => todo!(),
            Code::KEY_UNKNOWN => todo!(),
            Code::KEY_VIDEO_NEXT => todo!(),
            Code::KEY_VIDEO_PREV => todo!(),
            Code::KEY_BRIGHTNESS_CYCLE => todo!(),
            Code::KEY_BRIGHTNESS_AUTO => todo!(),
            Code::KEY_BRIGHTNESS_ZERO => todo!(),
            Code::KEY_DISPLAY_OFF => todo!(),
            Code::KEY_WWAN => todo!(),
            Code::KEY_WIMAX => todo!(),
            Code::KEY_RFKILL => todo!(),
            Code::KEY_MICMUTE => todo!(),
        }
        .to_owned()
    }
}
