use crate::key::Code;

use super::layout::KeyMap;

pub struct Azerty;

impl Azerty {
    pub const TO_CAPITALIZE: [Code; 26] = [
        Code::KEY_Q,
        Code::KEY_W,
        Code::KEY_E,
        Code::KEY_R,
        Code::KEY_T,
        Code::KEY_Y,
        Code::KEY_U,
        Code::KEY_I,
        Code::KEY_O,
        Code::KEY_P,
        Code::KEY_A,
        Code::KEY_S,
        Code::KEY_D,
        Code::KEY_F,
        Code::KEY_G,
        Code::KEY_H,
        Code::KEY_J,
        Code::KEY_K,
        Code::KEY_L,
        Code::KEY_Z,
        Code::KEY_X,
        Code::KEY_C,
        Code::KEY_V,
        Code::KEY_B,
        Code::KEY_N,
        Code::KEY_SEMICOLON, // M is moved in azerty
    ];

    fn shift(key: &Code, key_as_str: &str) -> String {
        if Self::TO_CAPITALIZE.contains(key) {
            return key_as_str.to_uppercase();
        }
        match key {
            Code::KEY_1 => "1",
            Code::KEY_2 => "2",
            Code::KEY_3 => "3",
            Code::KEY_4 => "4",
            Code::KEY_5 => "5",
            Code::KEY_6 => "6",
            Code::KEY_7 => "7",
            Code::KEY_8 => "8",
            Code::KEY_9 => "9",
            Code::KEY_0 => "0",
            Code::KEY_MINUS => "°",
            Code::KEY_EQUAL => "+",
            Code::KEY_SEMICOLON => ":",
            Code::KEY_LEFTBRACE => "¨",
            Code::KEY_RIGHTBRACE => "£",
            Code::KEY_APOSTROPHE => "%",
            Code::KEY_M => "?",
            Code::KEY_COMMA => ".",
            Code::KEY_DOT => "/",
            Code::KEY_SLASH => "§",
            Code::KEY_BACKSLASH => "µ",
            Code::KEY_102ND => ">",
            Code::KEY_KP0 => "<inser>",
            Code::KEY_KPCOMMA => "<delete>",
            _ => key_as_str,
        }
        .to_owned()
    }
}

impl KeyMap for Azerty {
    fn format(key: &Code, is_shifted: bool) -> String {
        let key_as_str = match key {
            Code::KEY_RESERVED => "<reserved>",
            Code::KEY_ESC => "<escape>",
            Code::KEY_1 => "&",
            Code::KEY_2 => "é",
            Code::KEY_3 => "\"",
            Code::KEY_4 => "'",
            Code::KEY_5 => "(",
            Code::KEY_6 => "-",
            Code::KEY_7 => "è",
            Code::KEY_8 => "_",
            Code::KEY_9 => "ç",
            Code::KEY_0 => "à",
            Code::KEY_MINUS => ")",
            Code::KEY_EQUAL => "=",
            Code::KEY_BACKSPACE => "<del>",
            Code::KEY_TAB => "<tab>",
            Code::KEY_Q => "a",
            Code::KEY_W => "z",
            Code::KEY_E => "e",
            Code::KEY_R => "r",
            Code::KEY_T => "t",
            Code::KEY_Y => "y",
            Code::KEY_U => "u",
            Code::KEY_I => "i",
            Code::KEY_O => "o",
            Code::KEY_P => "p",
            Code::KEY_LEFTBRACE => "^",
            Code::KEY_RIGHTBRACE => "$",
            Code::KEY_ENTER => "<enter>",
            Code::KEY_LEFTCTRL => "<lctrl>",
            Code::KEY_A => "q",
            Code::KEY_S => "s",
            Code::KEY_D => "d",
            Code::KEY_F => "f",
            Code::KEY_G => "g",
            Code::KEY_H => "h",
            Code::KEY_J => "j",
            Code::KEY_K => "k",
            Code::KEY_L => "l",
            Code::KEY_SEMICOLON => "m",
            Code::KEY_APOSTROPHE => "ù",
            Code::KEY_GRAVE => "²",
            Code::KEY_LEFTSHIFT => "<lshift>",
            Code::KEY_BACKSLASH => "*",
            Code::KEY_Z => "w",
            Code::KEY_X => "x",
            Code::KEY_C => "c",
            Code::KEY_V => "v",
            Code::KEY_B => "b",
            Code::KEY_N => "n",
            Code::KEY_M => ",",
            Code::KEY_COMMA => ";",
            Code::KEY_DOT => ":",
            Code::KEY_SLASH => "!",
            Code::KEY_RIGHTSHIFT => "<rshift>",
            Code::KEY_KPASTERISK => "*",
            Code::KEY_LEFTALT => "<lalt>",
            Code::KEY_SPACE => " ",
            Code::KEY_CAPSLOCK => "<capslock>",
            Code::KEY_F1 => "<F1>",
            Code::KEY_F2 => "<F2>",
            Code::KEY_F3 => "<F3>",
            Code::KEY_F4 => "<F4>",
            Code::KEY_F5 => "<F5>",
            Code::KEY_F6 => "<F6>",
            Code::KEY_F7 => "<F7>",
            Code::KEY_F8 => "<F8>",
            Code::KEY_F9 => "<F9>",
            Code::KEY_F10 => "<F10>",
            Code::KEY_NUMLOCK => "<numlock>",
            Code::KEY_SCROLLLOCK => "<scroll_lock>",
            Code::KEY_KP7 => "7",
            Code::KEY_KP8 => "8",
            Code::KEY_KP9 => "9",
            Code::KEY_KPMINUS => "-",
            Code::KEY_KP4 => "4",
            Code::KEY_KP5 => "5",
            Code::KEY_KP6 => "6",
            Code::KEY_KPPLUS => "+",
            Code::KEY_KP1 => "1",
            Code::KEY_KP2 => "2",
            Code::KEY_KP3 => "3",
            Code::KEY_KP0 => "0",
            Code::KEY_KPDOT => ".",
            Code::KEY_ZENKAKUHANKAKU => todo!(),
            Code::KEY_102ND => "<",
            Code::KEY_F11 => "<F11>",
            Code::KEY_F12 => "<F12>",
            Code::KEY_RO => todo!(),
            Code::KEY_KATAKANA => todo!(),
            Code::KEY_HIRAGANA => todo!(),
            Code::KEY_HENKAN => todo!(),
            Code::KEY_KATAKANAHIRAGANA => todo!(),
            Code::KEY_MUHENKAN => todo!(),
            Code::KEY_KPJPCOMMA => todo!(),
            Code::KEY_KPENTER => "<enter>",
            Code::KEY_RIGHTCTRL => "<rctrl>",
            Code::KEY_KPSLASH => "/",
            Code::KEY_SYSRQ => "<imp_syst>",
            Code::KEY_RIGHTALT => "<ralt>",
            Code::KEY_LINEFEED => todo!(),
            Code::KEY_HOME => "<home>",
            Code::KEY_UP => "<up>",
            Code::KEY_PAGEUP => "<page_up>",
            Code::KEY_LEFT => "<left>",
            Code::KEY_RIGHT => "<right>",
            Code::KEY_END => "<end>",
            Code::KEY_DOWN => "<down>",
            Code::KEY_PAGEDOWN => "<page_down>",
            Code::KEY_INSERT => "<insert>",
            Code::KEY_DELETE => "<delete>",
            Code::KEY_MACRO => todo!(),
            Code::KEY_MUTE => "<mute>",
            Code::KEY_VOLUMEDOWN => "<vol_down>",
            Code::KEY_VOLUMEUP => "<vol_up>",
            Code::KEY_POWER => "<power>",
            Code::KEY_KPEQUAL => "=",
            Code::KEY_KPPLUSMINUS => todo!(),
            Code::KEY_PAUSE => "<pause>",
            Code::KEY_SCALE => todo!(),
            Code::KEY_KPCOMMA => todo!(),
            Code::KEY_HANGEUL => todo!(),
            Code::KEY_HANGUEL => todo!(),
            Code::KEY_HANJA => todo!(),
            Code::KEY_YEN => todo!(),
            Code::KEY_LEFTMETA => "<lmeta>",
            Code::KEY_RIGHTMETA => "<rmeta>",
            Code::KEY_COMPOSE => "<compose>",
            Code::KEY_STOP => todo!(),
            Code::KEY_AGAIN => todo!(),
            Code::KEY_PROPS => todo!(),
            Code::KEY_UNDO => todo!(),
            Code::KEY_FRONT => todo!(),
            Code::KEY_COPY => todo!(),
            Code::KEY_OPEN => todo!(),
            Code::KEY_PASTE => todo!(),
            Code::KEY_FIND => todo!(),
            Code::KEY_CUT => todo!(),
            Code::KEY_HELP => todo!(),
            Code::KEY_MENU => todo!(),
            Code::KEY_CALC => todo!(),
            Code::KEY_SETUP => todo!(),
            Code::KEY_SLEEP => "<sleep>",
            Code::KEY_WAKEUP => todo!(),
            Code::KEY_FILE => todo!(),
            Code::KEY_SENDFILE => todo!(),
            Code::KEY_DELETEFILE => todo!(),
            Code::KEY_XFER => todo!(),
            Code::KEY_PROG1 => todo!(),
            Code::KEY_PROG2 => todo!(),
            Code::KEY_WWW => todo!(),
            Code::KEY_MSDOS => todo!(),
            Code::KEY_COFFEE => todo!(),
            Code::KEY_SCREENLOCK => todo!(),
            Code::KEY_ROTATE_DISPLAY => todo!(),
            Code::KEY_DIRECTION => todo!(),
            Code::KEY_CYCLEWINDOWS => todo!(),
            Code::KEY_MAIL => todo!(),
            Code::KEY_BOOKMARKS => todo!(),
            Code::KEY_COMPUTER => todo!(),
            Code::KEY_BACK => todo!(),
            Code::KEY_FORWARD => todo!(),
            Code::KEY_CLOSECD => todo!(),
            Code::KEY_EJECTCD => todo!(),
            Code::KEY_EJECTCLOSECD => todo!(),
            Code::KEY_NEXTSONG => todo!(),
            Code::KEY_PLAYPAUSE => todo!(),
            Code::KEY_PREVIOUSSONG => todo!(),
            Code::KEY_STOPCD => todo!(),
            Code::KEY_RECORD => todo!(),
            Code::KEY_REWIND => todo!(),
            Code::KEY_PHONE => todo!(),
            Code::KEY_ISO => todo!(),
            Code::KEY_CONFIG => todo!(),
            Code::KEY_HOMEPAGE => todo!(),
            Code::KEY_REFRESH => todo!(),
            Code::KEY_EXIT => todo!(),
            Code::KEY_MOVE => todo!(),
            Code::KEY_EDIT => todo!(),
            Code::KEY_SCROLLUP => todo!(),
            Code::KEY_SCROLLDOWN => todo!(),
            Code::KEY_KPLEFTPAREN => todo!(),
            Code::KEY_KPRIGHTPAREN => todo!(),
            Code::KEY_NEW => todo!(),
            Code::KEY_REDO => todo!(),
            Code::KEY_F13 => todo!(),
            Code::KEY_F14 => todo!(),
            Code::KEY_F15 => todo!(),
            Code::KEY_F16 => todo!(),
            Code::KEY_F17 => todo!(),
            Code::KEY_F18 => todo!(),
            Code::KEY_F19 => todo!(),
            Code::KEY_F20 => todo!(),
            Code::KEY_F21 => todo!(),
            Code::KEY_F22 => todo!(),
            Code::KEY_F23 => todo!(),
            Code::KEY_F24 => todo!(),
            Code::KEY_PLAYCD => todo!(),
            Code::KEY_PAUSECD => todo!(),
            Code::KEY_PROG3 => todo!(),
            Code::KEY_PROG4 => todo!(),
            Code::KEY_ALL_APPLICATIONS => todo!(),
            Code::KEY_DASHBOARD => todo!(),
            Code::KEY_SUSPEND => todo!(),
            Code::KEY_CLOSE => todo!(),
            Code::KEY_PLAY => todo!(),
            Code::KEY_FASTFORWARD => todo!(),
            Code::KEY_BASSBOOST => todo!(),
            Code::KEY_PRINT => todo!(),
            Code::KEY_HP => todo!(),
            Code::KEY_CAMERA => todo!(),
            Code::KEY_SOUND => todo!(),
            Code::KEY_QUESTION => todo!(),
            Code::KEY_EMAIL => todo!(),
            Code::KEY_CHAT => todo!(),
            Code::KEY_SEARCH => todo!(),
            Code::KEY_CONNECT => todo!(),
            Code::KEY_FINANCE => todo!(),
            Code::KEY_SPORT => todo!(),
            Code::KEY_SHOP => todo!(),
            Code::KEY_ALTERASE => todo!(),
            Code::KEY_CANCEL => todo!(),
            Code::KEY_BRIGHTNESSDOWN => todo!(),
            Code::KEY_BRIGHTNESSUP => todo!(),
            Code::KEY_MEDIA => todo!(),
            Code::KEY_SWITCHVIDEOMODE => todo!(),
            Code::KEY_KBDILLUMTOGGLE => todo!(),
            Code::KEY_KBDILLUMDOWN => todo!(),
            Code::KEY_KBDILLUMUP => todo!(),
            Code::KEY_SEND => todo!(),
            Code::KEY_REPLY => todo!(),
            Code::KEY_FORWARDMAIL => todo!(),
            Code::KEY_SAVE => todo!(),
            Code::KEY_DOCUMENTS => todo!(),
            Code::KEY_BATTERY => todo!(),
            Code::KEY_BLUETOOTH => todo!(),
            Code::KEY_WLAN => todo!(),
            Code::KEY_UWB => todo!(),
            Code::KEY_UNKNOWN => todo!(),
            Code::KEY_VIDEO_NEXT => todo!(),
            Code::KEY_VIDEO_PREV => todo!(),
            Code::KEY_BRIGHTNESS_CYCLE => todo!(),
            Code::KEY_BRIGHTNESS_AUTO => todo!(),
            Code::KEY_BRIGHTNESS_ZERO => todo!(),
            Code::KEY_DISPLAY_OFF => todo!(),
            Code::KEY_WWAN => todo!(),
            Code::KEY_WIMAX => todo!(),
            Code::KEY_RFKILL => todo!(),
            Code::KEY_MICMUTE => todo!(),
        };
        if is_shifted {
            Azerty::shift(key, key_as_str)
        } else {
            key_as_str.to_owned()
        }
    }
}
